# Generated by Django 4.1.2 on 2022-10-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solcitud',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=50)),
                ('sucursal', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('solicitante', models.CharField(max_length=50)),
                ('prioridad', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
