# Generated by Django 4.1.2 on 2022-10-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestSoli', '0002_alter_solcitud_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=50)),
                ('sucursal', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('solicitante', models.CharField(max_length=50)),
                ('prioridad', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Solcitud',
        ),
    ]
